apiVersion: backstage.io/v1alpha1
kind: Component
metadata:
  annotations:
    argocd/app-name: my-argoCD-component
  name: my-argoCD-component
spec:
  lifecycle: production
  owner: my-team
  type: service
